Updating the upgrade process document
Axway/open-banking-docs pull request #33
Opened 2022-04-25 16:46 UTC by rksakamoto

Including the v2.0 special procedures for ACP and APIM components

Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Does not have conflicts with the base branch
* [ ] Is clear and complete
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links
* [ ] Is discoverable and navigable

## Checklist for mergers

_This section is to be filled out by project maintainers only._

Before merging this PR, please make sure:

* [ ] You have applied a size label (unless this work is tracked in the ReadMeFirst JIRA project)
* [ ] You have applied a production label if this needs a manual push to Zoomin
* [ ] You have added it to the correct GitHub project
* [ ] You have added it to the correct Sprint milestone
* [ ] You have appended a `fixes` line to this description if this PR fixes a specific GitHub issue
* [ ] You have added a new collection to Netlify CMS config (static/admin/config.js) if required (new doc sections)
* [ ] You have updated the Zoomin classification file if required (new AMPC topics)

2022-04-25 19:22 UTC, sallylanda6 requested changes
I completed a copy edit for consistency and standards. I also added one question that may or may not need any changes.

2022-04-25 19:22 UTC, sallylanda6 commented on content/en/docs/deployment/upgrade.md
> +If you are upgrading the ACP components from previous releases previous than helmchart 2.0 , it is necessary to update the cockroachdb to v21.2 before the upgrade of acp package:
```suggestion
If you are upgrading the ACP components from previous releases before Helm chart v2.0, it is necessary to update the CockroachDB to v21.2 before you upgrade the acp package:

```

2022-04-25 19:22 UTC, sallylanda6 commented on content/en/docs/deployment/upgrade.md
> +If you are upgrading the ACP components from previous releases previous than helmchart 2.0 , it is necessary to update the cockroachdb to v21.2 before the upgrade of acp package:
The Installation topic refers to the ACP components (ACP and Consent) as Cloud Entity installation. Will users know that ACP components is Cloud Entity?

2022-04-25 19:22 UTC, sallylanda6 commented on content/en/docs/deployment/upgrade.md
> +After this it is ready to upgrade process.
```suggestion
```

2022-04-25 19:22 UTC, sallylanda6 commented on content/en/docs/deployment/upgrade.md
> +After this it is ready to upgrade process.
I don't think it's necessary to include that sentence.

2022-04-25 21:49 UTC, sallylanda6 commented on content/en/docs/deployment/upgrade.md
> +If you are migrating from version 1.3 to 1.4, the API management component has been split into two Helm charts: `apim` for products and `apim-config` for configuration. In this case you must therefor
Oops, I edited this incorrectly. I intended to delete the word "therefore" and not "uninstall." Please add "uninstall" back.

2022-04-28 13:18 UTC, rksakamoto reviewed
ok

2022-04-28 19:04 UTC, sallylanda6 approved these changes

2022-04-28 19:04 UTC, merged